### PR TITLE
Added the zeroStart option to all the line chart and set it to true by default.

### PR DESCRIPTION
**Pull request by nxanil**
@ronakmshah: Please review.

### CODE REVIEW

**Comment by ronakmshah** [comment]
@nxanil zeroStart's default value should be true and the viz config should not be required to add it unless they want to show negative y. What am I missing?

**Comment by nxanil** [comment]
@ronakmshah 
Yes, I agree. Updated it.
Just to let you know, zeroStart is for graphs where say minimum value of yaxis is greater than zero say from 30 to 100. Then in this case graph will start from 30 instead of zero and with zeroStart as true, it will be overridden and yAxis will start from 0.

**Comment by ronakmshah** [comment]
@nxanil agree. Thanks for taking care of this.

**Comment by ronakmshah** [comment]
@nxanil please merge the same code in 4.0

**Pull request merged**
