### PR TITLE
Brush in Bar Graph

### PR DESCRIPTION
**Pull request by nxanil**
@ronakmshah 
I have added brushing feature for bar charts.
To enable this feature set **brush** to true in the setting.
Please have a look.

screencapture-localhost-3000-dashboards-example-1512145541538

### CODE REVIEW

**Comment by ronakmshah** [comment]
@nxanil, @bmukheja please test this with scenario where you have 100 bars and you want to show 10 at a time.

**Comment by ronakmshah** [comment]
@nxanil, minor comment: The brush does not make sense if you have limited bars which can be fitted in one screen (potentially can be defaulted to 10 and be configured via visualizatons). So it is better to check for the result size before showing this. Make sense?

**Comment by bmukheja** [comment]
I will test the functionality, @ronakmshah Wouldn't it be good to have it automatically turn on brushing when number of bars is more than 10 or say 7? Because in case, if a query expects more than 10, and there are not enough entries in the search results, the bar would not serve a purpose and still show up.

Also the automatic appearance would save the otherwise 'break' of previous bar graph visualisations.

**Comment by nxanil** [comment]
@bmukheja @ronakmshah 

Changed the brush to numeric settings i.e. _brush: 10_, means whenever the bars reached to 10, brush will shown up. You can change 10 to whatever you would like to.

**Comment by ronakmshah** [comment]
@nxanil time to test this and merge it. Can you please rebase this so that I can play with it and than merge. Thanks

**Comment by nxanil** [comment]
@ronakmshah 

Merge branch 'master' into feature/dynamic-bar-graph.

**Comment by nxanil** [comment]
@ronakmshah Tooltip and Brush sorting has been fixed.

Still left with "Resizing the Brush Size"

**Comment by ronakmshah** [comment]
@nxanil I still see only 10 bar charts even though there are more than 10 entries that gets return per database.json.

**Comment by nxanil** [comment]
@ronakmshah 
We have 10 enteries only per Medal Category for particular year.
Currently database.json is used for 2012 only and only have 10 records in every category.

**Comment by nxanil** [comment]
@ronakmshah 

I have completed the task of resizing the Brush Size. 
Now `brush: 10` means brush will be applied to the bar graph if minimum 10 bars exists and that 10 bar will be pre-selected.

**Comment by ronakmshah** [comment]
@nxanil looks good. Please squash your multiple commits into 1 and we can merge this into master.

**Comment by nxanil** [comment]
@ronakmshah Done with squashing

**Pull request merged**
