### PR TITLE
Add a horizontal slider for time at the top of the heatmap: 419

### PR DESCRIPTION
**Pull request by nxanil**
@ronakmshah @sayaji15:

Please review.

### CODE REVIEW

**Comment by sayaji15** [comment]
image
 Looks good to me. Is there a way to make the x axis look less crowded

**Comment by nxanil** [comment]
@sayaji15: Made a change please verify whether this will work. Printed the label for alternate cell if  cell counts greater than 15 cells.

**Comment by sayaji15** [comment]
@nxanil I removed the filter options as it is not required for now
![image](https://user-images.githubusercontent.com/12192208/28891449-62bf77ae-777f-11e7-8d10-81f3e322cf25.png

Also the horizontal scroll is not working

**Comment by sayaji15** [comment]
@nxanil Can you prioritize this issue

**Comment by nxanil** [comment]
@sayaji15 Please verify this now.

**Comment by sayaji15** [comment]
image

The x axis still does not look right

**Comment by sayaji15** [comment]
@nxanil you have to set following variables. Lets say if we are looking at heatmap ending at time t1
then
aar-flow-sla-heatmap-endTime=t1
aar-flow-sla-heatmap-startTime=t1-15m
Also set aar-flow-sla-heatmap-interval to 30s for now. Eventually, this value will be passed into the visualization.

**Comment by nxanil** [comment]
@sayaji15 
I understand your point, but before working on that: I have made a push such that I am showing all the label for all the cells available, and along with it I have tilted the label as well. Could you please have a glance at it?

**Comment by sayaji15** [comment]
@nxanil I rebased this PR with master branch to take your changes. But now the onclick fucntionality
does not work. I cannot select from nsg and to nsg tables for the heatmap.
This is the branch feature/419_heatmap_scroll_merge. Can you please confirm if I have merged everything correctly.

**Comment by nxanil** [comment]
@sayaji15 ,
I have resolved the on-click issue.

**Comment by sayaji15** [comment]
@nxanil thanks

**Pull request closed without merging**
