### PR TITLE
[Bug]: VSD empty data issue #699

### PR DESCRIPTION
**Pull request by nxanil**
@bmukheja 

Please have a look and let me know the issue is fixed or not?

### CODE REVIEW

**Comment by natabal** [comment]
@nxanil This type of change we cannot push in last minute without testing more. It affects all the queries

**Comment by nxanil** [comment]
@natabal: Ok, sure! But I believe, it is not going to cause any side effects, as it is just an additional check.

**Comment by natabal** [comment]
@nxanil How are the other queries handling this issue?

**Comment by nxanil** [comment]
@natabal 
In ES, we already tabify the data to handle such error and in VSD this error occurred first time so we also put check for undefined data.

**Comment by natabal** [comment]
@nxanil Is this to be closed?

**Comment by bmukheja** [comment]
@nxanil - It is still happening. Can you check.

**Comment by nxanil** [comment]
@bmukheja Are you testing in this branch?

**Comment by natabal** [comment]
@nxanil Is this something that needs to be merged now?

**Comment by bmukheja** [comment]
It's already been merged. Closing.

**Pull request closed without merging**
