### PR TITLE
Added dynamic filter option

### PR DESCRIPTION
**Pull request by nxanil**
@ronakmshah 

Follow the README.md instructions for "Dynamic Filter" 
**queryKey** is the key that will tell the name of the query to be used
**label** and **value** respectively define the fields to be used from results

### CODE REVIEW

**Comment by anilkchauhan** [comment]
@ronakmshah I have merged your PR into this, and worked on the top of that.
Could you please check it?

**Comment by nxanil** [comment]
@ronakmshah I have merged your PR into this and worked on the top of that.
Could you please check it?

**Comment by nxanil** [comment]
@ronakmshah sample configuration will be like:

"filterOptions": {
        "Flag-Type": {
            "parameter": "flagtype",
            "default": "SYN",
            "options": [
                {
                    "label": "SYN",
                    "value": "SYN",
                    "default": true
                },
                {
                    "label": "SYN-ACK",
                    "value": "SYN-ACK"
                },
                {
                    "label": "SYN-ACK",
                    "onChange": "Categories" 
                }
            ]
        },
        "Categories": {
            "parameter": "flagtype",
            "default": "SYN",
            "dynamicOptions": { // Dynamic filter option
                "queryKey":  "context", // query key - refer to query section
                "label": "response.label", // key to be used from from "context" query response
                "value": "response.timestamp", // key to be used from from "context" query response
                "forceOptions": { // optional
                    "destination_field": "response.param1" // key to be used from from "context" query response,
                    "destination_field1": "response.param2" // key to be used from from "context" query response
                }
            },
            "options": [
                {
                    "label": "SYN",
                    "value": "SYN",
                    "default": true
                },
                {
                    "label": "SYN-ACK",
                    "value": "SYN-ACK"
                }
            ]
        }
    },
    "query": {
        "data": "vss-domain-traffic-tcp-syn",
        "context": "vnf-status" // this key will be used in the "dynamic option" - can be anything used over here
    }

Let me know if it make sense to you.

**Comment by nxanil** [comment]
@ronakmshah 
Added following option in Query:
[Screenshot from Gyazo](https://gyazo.com/c88cedc2b731cff62dd5d810d0b2366a)

Now to replace them add respective replace option in the "visualization" json file and must match the value you added in "query" file for replacing.
[Screenshot from Gyazo](https://gyazo.com/c6ee3527e0f44c07a7ebfc3a9fcb9fe9)

**Comment by nxanil** [comment]
@ronakmshah 
Please note, if the context is there in the URL then only replace will work, otherwise remove it.

**Comment by ronakmshah** [comment]
@nxanil What will you do with the extra ","  at the bool query level? Wouldnt that be a problem

**Comment by ronakmshah** [comment]
TRACE: 2018-07-06T16:37:27Z
  -> POST http://135.227.179.12:9200/nuage_flow/nuage_doc_type/_search
  {
    "size": 0,
    "query": {
      "bool": {
        "must": [
          {
            "range": {
              "timestamp": {
                "gte": "now-24h",
                "lte": "now",
                "format": "epoch_millis"
              }
            }
          },
          {
            "term": {
              "nuage_metadata.enterpriseName": "vss-corp"
            }
          },
          {
            "term": {
              "nuage_metadata.domainName": "vcs-domain"
            }
          },
          {
            "replace": "src-pg-membership"
          },
          {
            "replace": "dst-pg-membership"
          }
        ]
      }
    },
    "aggs": {
      "hash": {
        "terms": {
          "field": "nuage_metadata.flowid",
          "size": 10,
          "order": {
            "SumOf": "desc"
          }
        },
        "aggs": {
          "SumOf": {
            "sum": {
              "field": "packets"
            }
          },
          "source": {
            "terms": {
              "field": "nuage_metadata.src-pgmem.name",
              "size": 10,
              "order": {
                "SumOf": "desc"
              }
            },
            "aggs": {
              "SumOf": {
                "sum": {
                  "field": "packets"
                }
              }
            }
          },
          "destination": {
            "terms": {
              "field": "nuage_metadata.dst-pgmem.name",
              "size": 10,
              "order": {
                "SumOf": "desc"
              }
            },
            "aggs": {
              "SumOf": {
                "sum": {
                  "field": "packets"
                }
              }
            }
          }
        }
      }
    }
  }
  <- 400
  {
    "error": {
      "root_cause": [
        {
          "type": "parsing_exception",
          "reason": "[replace] query malformed, no start_object after query name",
          "line": 1,
          "col": 231
        }
      ],
      "type": "parsing_exception",
      "reason": "[replace] query malformed, no start_object after query name",
      "line": 1,
      "col": 231
    },
    "status": 400
  }

**Comment by nxanil** [comment]
@ronakmshah 

Fixed dropdown alignment and array inside result. Please have a look

**Comment by nxanil** [comment]
@ronakmshah 

Fixed query replace issue. Please have a look.

**Pull request merged**
