### PR TITLE
Enhancement/update packages

### PR DESCRIPTION
**Pull request by nxjiten**
@natabal 

Update the react version `16.6.3` and its dependent packages. Please have a look.

### CODE REVIEW

**Comment by bmukheja** [comment]
Hi @nxjiten, I'm adding all the bugs down below in the comments one by one, please have a look at them.

**Comment by bmukheja** [comment]
1. When switching dashboards. the screen goes blank and it says "No Dashboard" and the dashboard comes back if the page is refreshed.
image

**Comment by natabal** [comment]
@nxjiten Can you please fix this so we can merge this is master? Thanks

**Comment by bmukheja** [comment]
2. This error on infraRegressResults dashboard -
Objects are not valid as a React child (found: object with keys {testcase, doc_count, notrun-bucket, pass-bucket, fail-bucket, pass, fail, notrun}). If you meant to render a collection of children, use an array instead.
    in div (created by Tooltip)
    in Tooltip (at Table/index.js:413)
    in td (created by DataTablesRowColumn)
    in DataTablesRowColumn (created by DataTables)
    in tr (created by DataTablesTableRow)
    in DataTablesTableRow (created by DataTables)
    in tbody (created by DataTablesTableBody)
    in ClickAwayListener (created by DataTablesTableBody)
    in DataTablesTableBody (created by DataTables)
    in table (created by DataTablesTable)
    in div (created by DataTablesTable)
    in div (created by DataTablesTable)
    in DataTablesTable (created by DataTables)
    in div (created by DataTables)
    in DataTables (at Table/index.js:997)
    in div (at Table/index.js:981)
    in MuiThemeProvider (at Table/index.js:980)
    in Table (at Visualization/index.js:333)
    in div (created by CardText)
    in CardText (at Visualization/index.js:586)
    in div (at Visualization/index.js:579)
    in div (created by Card)
    in div (created by Paper)
    in Paper (created by Card)
    in Card (at Visualization/index.js:573)
    in VisualizationView (created by Context.Consumer)
    in Connect(VisualizationView) (at Dashboard/index.js:207)
    in div (at Dashboard/index.js:203)
    in GridItem (created by ReactGridLayout)
    in div (created by ReactGridLayout)
    in ReactGridLayout (created by ResponsiveReactGridLayout)
    in ResponsiveReactGridLayout (created by _class)
    in _class (at Dashboard/index.js:193)
    in div (at Dashboard/index.js:192)
    in div (at Dashboard/index.js:188)
    in DashboardView (created by Context.Consumer)
    in Connect(DashboardView) (created by Route)
    in Route (at App.js:18)
    in div (at AppContainer.js:62)
    in div (at AppContainer.js:59)
    in div (at AppContainer.js:79)
    in MuiThemeProvider (at AppContainer.js:78)
    in AppContainerView (created by Context.Consumer)
    in Connect(AppContainerView) (at App.js:16)
    in MuiThemeProvider (at App.js:15)
    in App (at src/index.js:15)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Context.Consumer)
    in Connect(ConnectedRouterWithContext) (at src/index.js:14)
    in Provider (at src/index.js:13)
▶ 48 stack frames were collapsed.
(anonymous function)
src/redux/middlewares.js:8
   5 | // TODO: We need to find a way to plug middlewares like this one.
   6 | // as it is very specific to Nuage features (VSS or AAR)
   7 | export const updateVisualizationTypeMiddleware = store => next => action => {
>  8 |     const result = next(action),
   9 |           state  = store.getState();
  10 |     if (action.type === "@@router/LOCATION_CHANGE" && state.router && state.router.action !== 'pop' && state.router.location.query && state.router.location.pathname.indexOf('dashboards') !== -1)
  11 |     {
View compiled
(anonymous function)
src/redux/middlewares.js:29
  26 | }
  27 | 
  28 | export const updateContextMiddleware = store => next => action => {
> 29 |     const result = next(action),
  30 |           state  = store.getState();
  31 | 
  32 |     if (action.type === "@@router/LOCATION_CHANGE" && state.router) {
View compiled
▶ 4 stack frames were collapsed.
_callee$
src/services/servicemanager/redux/actions.js:183
  180 |             ))
  181 |         }
  182 | 
> 183 |         dispatch(didReceiveResponse(requestID, data, forceCache))
      | ^  184 | 
  185 |         return Promise.resolve(data);
  186 | },
View compiled
▶ 5 stack frames were collapsed.

**Comment by bmukheja** [comment]
Rest all looks good.

**Comment by nxjiten** [comment]
@natabal @bmukheja 

Fix "no dashboard" issue on toggle dashboards.

Also, I am not able to reproduce the console error, so it would be great if you will provide the table configuration and query response of the infraRegressResults dashboard so that I can test it at my end.

**Comment by bmukheja** [comment]
@nxjiten - Getting this error -
image

**Comment by bmukheja** [comment]
Hi @nxjiten - the issues with the dashboard have been resolved by changing to customTabify, we'll analyse what went wrong in the common tabification later, for now merging this PR as the above error has been resolved.

**Pull request merged**
