### PR TITLE
WIP: Feature/vnf

### PR DESCRIPTION
**Pull request by ronakmshah**

### CODE REVIEW

**Comment by ronakmshah** [comment]
@nxanil over to you for the fixes that we talked about offline.

**Comment by nxanil** [comment]
@ronakmshah 
Gauge issue is fixed now please have a look.

**Comment by ronakmshah** [comment]
@nxanil thanks. I will take a look. I was thinking if we can add an actual value at the bottom of the gauge chart! That would be intuitive.

**Comment by nxanil** [comment]
@ronakmshah 
Please review these points:

1. minimum value that I am seeing is 0.0 . It should be 0 without a decimal point.
2. We should color code 0 as Red and 100 as Green and the shades of lighter Reds as it increases with getting changed into yellow and than the shades of green.
3. When the graph is loaded, is it possible to show the niddle being moved dynamically? Starts from 0 and increases towards its value.
4. Show the currentValue as an absolute value under the chart to see what exactly it is.
It would be nicer if that is also changing dynamically as the niddle moves as part of 3.

**Comment by nxanil** [comment]
@ronakmshah 
Please try it now and let me know if it works.

**Comment by ronakmshah** [comment]
@nxanil the gauge chart looks ok now. I think it is a good time to merge these changes and move onto fixing the multi-line chart issue to complete the dashboard.

**Comment by ronakmshah** [comment]
@nxanil for the vnf dashboard I would like to reverse the colors on the gauge where green to red happens from 0 to 100. How can one add that order in the visualization configuration?

**Comment by nxanil** [comment]
@ronakmshah I have resolved the conflicts. Please check.

**Comment by ronakmshah** [comment]
This looks good now. Good work @nxanil

**Pull request merged**
