### PR TITLE
Feature/table changes

### PR DESCRIPTION
**Pull request by nxanil**
@ronakmshah @bmukheja 

1) I have added a feature to hide pagination and search bar if there is just one page only as per defined limits
By default this feature is enabled, to disable this feature please set **hidePagination** to false in settings.

2) To highlight the rows if data of given column is not null, please set **highlight** in settings and pass number of column(s) as an array.
For e.g - "highlight": ["top-acl-hits.sort", "top-acls"]

screencapture-localhost-3000-visualizations-vss-domain-acl-top5-1512401667747

3) Click issue on row also has been fixed. 

Please review

### CODE REVIEW

**Comment by nxanil** [comment]
@ronakmshah @bmukheja 
This the PR for click issue on table row.

**Comment by bmukheja** [comment]
@natabal @nxanil - Is the default row count of table set to 5 rows? Kindly refer to the above image, we need more rows to fill till bottom.

**Comment by nxanil** [comment]
@bmukheja 
Please check it now.

**Comment by bmukheja** [comment]
Working Fine

**Pull request merged**
