### PR TITLE
Area graph component added

### PR DESCRIPTION
**Pull request by nxanil**

### CODE REVIEW

**Comment by nxanil** [comment]
@bmukheja 
Added the tooltip and fontsize options.
For fontsize you can set following parameters:

-  xTickFontSize,  yTickFontSize

**Comment by nxanil** [comment]
@bmukheja Please review the coloring and  starting and ending of line from xAxis..

**Comment by nxanil** [comment]
@bmukheja @ronakmshah Please review stacked area chart.

Added default  config "stacked" to true, to enable stack area chart by default. You can turn it to off to have overlapping behaviour.

**Comment by bmukheja** [comment]
@nxanil The stacking is working, but one thing remains is the placing of the individual component. It would be better to see it all sorted, as in the smallest value at the bottom and the highest at the top. It would save confusion from discontinuous graphs like this
image
If you notice, the MSOffice365 has a discontinuous area and sticks out. It should be at the bottom fow a more polished view.

**Pull request merged**
