### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by nxanil**
@ronakmshah 
Updated the README.md for missing features(options).

### CODE REVIEW

**Comment by nxanil** [comment]
@ronakmshah You can merge it as it is related to DOCS enhancment only.

**Comment by bmukheja** [comment]
@nxanil _ Updating the things discussed in the meeting today.

Please add the details for the below:

1. Padding
2. Margin

**Comment by nxanil** [comment]
@bmukheja 

There is already a doc for padding and margin, please let me know in point 1 and 2 are the same docs in below screenshot or this is different one?

padding-margin

**Comment by bmukheja** [comment]
@nxanil - Can you please fill in what components get affected by each of them, thanks.

**Comment by bmukheja** [comment]
@nxanil - Is the padding and margin functionality fully working? I've had this error earlier also, posting it now. 
image

Margin is the same for "0" ,"10px" and "50px"

Below is the key values being used - 

"margin": {
            "top": "auto",
            "bottom": "auto",
            "left": "10px",
            "right": "auto"
     },

**Comment by nxanil** [comment]
@bmukheja 

Here margin is being used to calculate the height and width of the graph and some other mathematical calculations, so we should only given integer values in margins as given below: -

`"margin": {
      "top": 20,
      "bottom": 20,
      "left": 50,
      "right": 50
  }`

The impact to change in margin is shown in below screenshot - 

margin-example png

**Comment by bmukheja** [comment]
@nxanil - I'm still unsure about the functionality of margin. Does it calculate the distance of the y-column labels or from the leftmost-edge of the graph? In case of the former it doesn't present any use since label names are going to be variable by default in case of aggregating from elasticsearch.

**Pull request merged**
