### PR TITLE
Fixed color in heatmap based on predefined results

### PR DESCRIPTION
**Pull request by nxanil**
@ronakmshah , @bmukheja 

Fixed issue of color in the heatmap. Please review

heatmap

### CODE REVIEW

**Comment by bmukheja** [comment]
@nxanil There is a bug in this currently where it still picks up the first color defined in "otherColors" for the key of "0".

**Comment by nxanil** [comment]
@bmukheja 
The issue has been fixed. Please check now.

**Comment by bmukheja** [comment]
Yes, it's working fine now. Let's complete this feature as a whole and implement the color selection feature. Then we'll merge this.

**Comment by nxanil** [comment]
@bmukheja 
Make this feature as a whole.
To do this,  you have to define `heatmapColor` in visualization file to merge from  `mapColors`. For e.g - 
`"heatmapColor": {
            "InSla": "#b3d645"
        }`

**Pull request merged**
