### PR TITLE
GIT 363 & 364 - Heatmap Issues related to Uneven Size and X-Axis issue

### PR DESCRIPTION
**Pull request by nxanil**
@divyahc Please check issues number 363 and 364.

### CODE REVIEW

**Comment by divyahc** [comment]
@nxanil could you please merge the changes

**Comment by nxanil** [comment]
@divyahc - Do you mean you have reviewed and it and we have to merge it into master?
I have merged all the recent changes from master branch into this.

**Comment by ronakmshah** [comment]
@divyahc has verified this. Merging this in.

**Comment by ronakmshah** [comment]
@nxanil can you also merge this change in 4.0 branch?

**Pull request merged**
