### PR TITLE
Column dropdown option

### PR DESCRIPTION
**Pull request by nxanil**
@ronakmshah 

Added column drop-down options to display selected columns in a table.
To enable this feature, set `selectColumnOption: true` and In columns array set `display: false` to hide any column from a table (default is true, i.e. column will display inside the table if `display` is missing or set to `true`).

2205b13367443b576bf16decb6f7d144

d8405e927995a1df2933e86c8ec152a1

### CODE REVIEW

**Comment by ronakmshah** [comment]
This is great. Let me test this out and select default columns post you fix conflict @nxanil. 
We will merge this post the next release though.

**Comment by nxanil** [comment]
@ronakmshah 
Resolved conflicts.

**Comment by ronakmshah** [comment]
@nxanil can we fix the conflict and merge this in master

**Comment by nxanil** [comment]
@ronakmshah 
Merged into master.

**Pull request merged**
